=== bracketbear/website-monorepo/apps/portfolio/.astro/collections/workJobs.schema.json
{
  "$ref": "#/definitions/workJobs",
  "definitions": {
    "workJobs": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "company": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "highlights": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "startDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date-time"
            },
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "integer",
              "format": "unix-time"
            }
          ]
        },
        "endDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date-time"
            },
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "integer",
              "format": "unix-time"
            }
          ]
        },
        "workSkills": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "isCurrentJob": {
          "type": "boolean",
          "default": false
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "company",
        "startDate"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== bracketbear/website-monorepo/apps/cms/content/work/jobs/mtl-full-stack-developer.json
{
  "title": "Full Stack Web Developer",
  "company": "molecular-testing-labs",
  "description": "Launched sites tied to a LIMS back end, migrated legacy properties, and implemented HIPAA-compliant workflows.",
  "highlights": [
    "Spearheaded the development and launch of several new websites to support the business' expansion into emerging markets",
    "Interfaced with executive leadership teams in organizations such as Blue Cross Blue Shield of America, The Kathy Ireland Foundation, and EverlyWell",
    "Designed and implemented a robust back-end system that facilitated seamless communication between multiple websites and the company's proprietary laboratory information management system",
    "Successfully migrated multiple existing websites to a new LAMP server and implemented HIPAA-compliant protocols to ensure data security and privacy",
    "Collaborated with the Business Development team to develop and execute a range of innovative marketing strategies, increasing product and business exposure"
  ],
  "startDate": "2016-03-01",
  "endDate": "2020-01-01",
  "isCurrentJob": false,
  "workSkills": [
    "react",
    "css",
    "html",
    "javascript",
    "php",
    "mysql",
    "laravel",
    "git",
    "docker"
  ]
}
